# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

include: "rules/common.smk"
include: "rules/kallisto.smk"


rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.
        "resources/kb/index.idx",
        "resources/kb/t2g.txt"


include: "rules/other.smk"
